// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nkcgmbjaimrgapdnaqrc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rY2dtYmphaW1yZ2FwZG5hcXJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNTQ3ODQsImV4cCI6MjA3MzkzMDc4NH0.o6M_etzbp1wCtrxoZPOG7bNuNXFzTGwGlOwpcXnSa3A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});