// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irwlzrgjvblvjixbxcup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlyd2x6cmdqdmJsdmppeGJ4Y3VwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MjUyNTUsImV4cCI6MjA3MzIwMTI1NX0.XEw62dBRkQFaTJr4Cxa3mar9aiAs2X_a42dY6BKblBA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});